# Generated by Django 5.2.7 on 2025-10-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Pharmaceuticals', 'Pharmaceuticals'), ('Medical Equipment', 'Medical Equipment'), ('Surgical Supplies', 'Surgical Supplies'), ('Lab Supplies', 'Lab Supplies'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
